name: CI
on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9]+'
jobs:
  Test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        jdk: [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-${{ matrix.jdk }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run tests
        run: mvn -q clean verify -B
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.4
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: '**/surefire-reports/*.xml'
          report_individual_runs: true
